### PR TITLE
Avoid errors on incomplete URLSearchParams implementations

### LINKED ISSUE #985: searchParams fails with Servo (and maybe webkit?)
Servo now includes `searchParams`, but it fails with: `searchParams[Symbol.iterator] is not a function`. Maybe because it's an older spidermonkey. Not sure.

Anyway, this also appears to fail with Chrome:

```js
var searchParams = new URL("http:x.com/?x=y").searchParams;
for (var p of searchParams) {
  console.log(p);
}
```

### PR DESCRIPTION
**Pull request by Gozala**
- WebKit does not even have `window.URLSearchParams` so attempt to construct was throwing an error.
- Servo does no implement iteration protocol for `URLSearchParams[Symbol.iterator]` so attempt to iterate was throwing.

Fixes #985

### CODE REVIEW

File: src/common/runtime.js [hunk 1]
```diff
@@ -187,14 +187,10 @@ export const useNativeTitlebar =
...
   () => {
-    const env = Object.create(null);
     const url = URL.parse(window.location.href);
     const params = url.searchParams;
-    // @Hack: On servo searchParams don't show up (See  servo/servo#10335)
-    if (params == null) {
-      return QueryString.parse(url.search.substr(1));
-    }
-    else {
+    try {
```
Comment (tschneidereit) [inline src/common/runtime.js]: The only way this would throw is because of the missing `Symbol.iterator`, right? If so, I'd prefer to test for that instead of the `try` block:
```js
if (params[Symbol.iterator]) {
  ..
} else {
  return QueryString.parse(url.search.substr(1));
}
```

**Comment by tschneidereit** [comment]
r=me with the comment addressed.
